### ISSUE TITLE
Sync zen-window and source window after restoring

### ISSUE THREAD

**Issue by timsofteng** [folke/zen-mode.nvim#19]
Hey. After closing zen-mode window restores with it previous state. I mean cursor position and buffer (file) content.
Is it possible to implement option to sync ordinary window with zen-window after restoring? 
Imagine you go to definition from zen-mode buffer to another and then exit zen-mode. You will see your previous buffer...
Hope you'll get what I mean.

**Comment by nasanos** [comment]
Agree that it would be great if, when exiting zen-mode, your cursor position carried over to the original window. I find it tedious to have to find my position again after leaving zen-mode.

To that end, I added a line to the `close` function in my `view.lua`. It uses `nvim_win_get_cursor` and `nvim_win_set_cursor`. So far, it's working well!

I'm submitting a PR now with that change, in case anyone is interested in using it.

**Comment by timsofteng** [comment]
@nasanos cool!
But I believe it's not enough. We need to track buffer changing as well.

**Comment by nasanos** [comment]
Yeah, I noticed your other concern, but I don't think I've personally noticed any issues with buffer changes not being tracked.

Do you have an example to look at? I can't guarantee that I can work out a fix or anything, but at least that way maybe others can get a better idea for what the problem is and what to do about it.

**Comment by timsofteng** [comment]
@nasanos Just activate zenmode and open another file in buffer. Than close zenmode.

**Comment by timsofteng** [comment]
@nasanos Hello. May you please take a look at this issue? Thanks!

**Comment by nasanos** [comment]
@timsofteng Testing this again, the final version of the code in my PR #37 seems to accomplish what you're looking for.
1. Open a buffer, *Buffer A*.
1. Activate zen-mode.
1. Change the buffer (by opening a file or otherwise), *Buffer B*.
1. Deactivate zen-mode.
1. Verify that the current display:
    - Consists of *Buffer B*
    - Retains the cursor position from zen-mode

In my testing, that all holds true when using the following code block I'd implemented in `view.lua`.
```
  if M.parent and M.win then
    -- Ensure that the parent window has the same buffer
    -- as the zen-mode window.
    if vim.api.nvim_win_get_buf(M.parent) ~= vim.api.nvim_win_get_buf(M.win) then
      vim.api.nvim_win_set_buf(M.parent, vim.api.nvim_win_get_buf(M.win))
    end
    -- Then, update the parent window's cursor position.
    vim.api.nvim_win_set_cursor(M.parent, vim.api.nvim_win_get_cursor(M.win))
  end
```

It's the `if vim.api.nvim_win_get_buf(M.parent) ~= vim.api.nvim_win_get_buf(M.win)` block in there that should force the parent window to use the zen-mode buffer if it isn't already doing so.

However, that block and the particular piece of behavior you're asking for were removed by @folke in commit a3c5dc2. So you may have to inquire with folke to determine how this behavior may or may not fit with the vision for the plugin.

You can, in the meanwhile, use the block above in your own local `view.lua` file to get the whole behavior you're after — just follow the placement you see in my PR's code changes. Local changes like this should hold until you update the plugin again, at which time you may have to again make the changes to your local `view.lua` file. (This is what I've done for my local zen-mode plugin.)

**Comment by timsofteng** [comment]
@nasanos Thanks for this information!

@folke May we merge this code to the project?
