### ISSUE TITLE
How to Exit ZenMode With ':q'?

### ISSUE THREAD

**Issue by FOSSilizedDaemon** [folke/zen-mode.nvim#35]
I noticed that `zen-mode` simply untoggles itself when exiting a buffer running `zen-mode` with `:q`. This seems to be common in Goyo-like plugins, but as I use `zen-mode` for mainly writing this leads to me having to exit twice. Is there any official way to have `:q` and `ZQ` and such exit `zen-mode` instead of toggling it?

**Comment by folke** [comment]
You could do `:qa` instead?

**Comment by SamLubbers** [comment]
I had the same problem as @FOSSilizedDaemon: when I execute `:q`, rather than exiting zen mode, I wish to quit the buffer (and hide it, as I use `set hidden`). Using `:qa` doesn't solve the problem because it will close all buffers and close vim (instead of just quitting the buffer I'm editing).

To get this to work, I learned from [this related code for the goyo plugin](https://github.com/junegunn/goyo.vim/wiki/Customization#ensure-q-to-quit-even-when-goyo-is-active), and added this code to the zen mode callbacks:

```lua
require("zen-mode").setup {
  on_open = function(_)
    vim.cmd 'cabbrev <buffer> q let b:quitting = 1 <bar> q'
    vim.cmd 'cabbrev <buffer> wq let b:quitting = 1 <bar> wq'
  end,
  on_close = function()
    if vim.b.quitting == 1 then
      vim.b.quitting = 0
      vim.cmd 'q'
    end
  end,
}
```

@folke why doesn't zen mode automatically exit plugins with `:q`? I think that would be useful so that `:q` still works the same as in regular buffers, and then `:ZenMode` is the command used to toggle zen mode.
