### ISSUE TITLE
Allow to preserve every UI elements

### ISSUE THREAD

**Issue by noomly** [folke/zen-mode.nvim#64]
I am trying to improve my prose writing setting and one thing I want to do is stop relying on hard text wrapping because of the inconvenience of having to join the lines before copy/pasting to other software.

The issue with the soft wrap approach is that there is currently no way of soft wrapping at an arbitrary width which result in lines being uncomfortably long. There is an opened issue on Neovim's repo but it's not getting any attention (https://github.com/neovim/neovim/issues/4386) and as far as I know there is no effort made in this direction.

Zen-mode actually solves this issue by allowing to resize the window & center it. The only issue with Zen-mode is that it hides all UI elements of Neovim by default, without any option to prevent it, which makes it unusable for me...

How hard would it be to make hiding the UI optional? If you don't have enough time to work on this but would accept a PR, could you point me in the right direction?

**Comment by gsbabil** [comment]
Hi @noomly @folke 

On a related note, is it possible to enable soft wrapping when zen mode
is enabled and go back to whatever state soft wrapping was in before
turning on zen mode?

I see that we have `on_open` and `on_close` callbacks, but I am not sure
if they allow saving the soft wrapping state in `on_open` so that we can
go back to the appropriate previous state at `on_close`.

Thank you!

**Comment by corani** [comment]
@gsbabil that is possible:

```lua
local oldwrap = vim.wo.wrap

require("zen-mode").setup {
    -- ...
    on_open = function(win)
        oldwrap = vim.wo.wrap
        vim.wo.wrap = true
    end,
    on_close = function()
        vim.wo.wrap = oldwrap
    end,
}
```
